### ISSUE TITLE
Update GTK themes to match QML and Kvantum styling

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-gtk-themes#4]
The GTK themes do not exactly match the styling of the QML Applications in NItrux or the KVantum theme. Both themes must be updated.

![image](https://user-images.githubusercontent.com/3053525/87377766-f748fd00-c551-11ea-916a-ace72af11e6b.png)
> Top are Kvantum, bottom are GTK.

The background color of the button is `#3a3f41`
The background color of the button when pressed is `#26C6DA`
The border of the button is `#61686b`
The radius is 4px

**Comment by lslvr** [comment]
Shiiiiiped!
